"""Fill the memo, evaluation page, and README measured blocks from harness JSON."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
SQ = HERE / "signal_quality" / "results"
LA = HERE / "label_availability" / "results"
PK = HERE / "pkpd_validation" / "results"
OP = HERE / "operating_point" / "results"


def _read(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))  # type: ignore[no-any-return]


def _table(md: str, startswith: str) -> str:
    lines = md.splitlines()
    start = next(i for i, line in enumerate(lines) if line.startswith(startswith))
    return "\n".join(line for line in lines[start:] if line.startswith("|") or line == "")


def render_memo() -> str:
    template = (HERE / "templates" / "research-memo.md").read_text(encoding="utf-8")
    sq = _read(SQ / "results.json")
    la = _read(LA / "results.json")
    pk = _read(PK / "results.json")
    op = _read(OP / "results.json")
    sq_md = (SQ / "results.md").read_text(encoding="utf-8")
    la_md = (LA / "results.md").read_text(encoding="utf-8")
    pk_md = (PK / "results.md").read_text(encoding="utf-8")
    op_md = (OP / "results.md").read_text(encoding="utf-8")
    cost = (
        "- Sample rebuild: five 60 s synthetic excerpts, committed, no network.\n"
        f"- Label index: {la['n_index']} synthetic rows, seed 0.\n"
        f"- PK/PD model: {pk['model']}.\n"
        "- VitalDB rsync time/size: unmeasured.\n"
        "- No API calls."
    )
    return (
        template.replace("{{SQI_TABLE}}", _table(sq_md, "| case"))
        .replace("{{SQI_DECISION}}", str(sq["decision"]))
        .replace("{{LABEL_TABLE}}", _table(la_md, "| set"))
        .replace("{{LABEL_DECISION}}", str(la["decision"]))
        .replace("{{PKPD_TABLE}}", _table(pk_md, "| predictor"))
        .replace("{{PKPD_DECISION}}", str(pk["decision"]))
        .replace(
            "{{SQI_SUMMARY}}",
            f"Artifact rejected={sq['artifact_rejected']}; "
            f"flush not called hypotension={sq['flush_not_called_hypotension']}; "
            f"dropout gaps reported={sq['dropout_gaps_reported']}.",
        )
        .replace(
            "{{LABEL_SUMMARY}}",
            f"Awareness labels: {la['n_index_awareness']}/{la['n_index']} index, "
            f"{la['n_samples_awareness']}/{la['n_samples']} samples. "
            f"Pivot to over-sedation={la['pivot_to_over_sedation']}.",
        )
        .replace(
            "{{PKPD_SUMMARY}}",
            f"corr(Ce, depth)={pk['corr_ce_vs_depth']:.3f}; "
            f"corr(rate, depth)={pk['corr_rate_vs_depth']:.3f}; "
            f"diverged_after_bolus={pk['diverged_after_bolus']}.",
        )
        .replace(
            "{{OP_SUMMARY}}",
            f"chosen Ce threshold={op['chosen_threshold']:.1f}; "
            f"TPR={op['chosen_tpr']:.3f}; FPR={op['chosen_fpr']:.3f}.",
        )
        .replace("{{OP_TABLE}}", _table(op_md, "| Ce"))
        .replace("{{OP_DECISION}}", str(op["decision"]))
        .replace("{{COST_MODEL}}", cost)
    )


def render_eval() -> str:
    return (
        "# Evaluation (Phase 0)\n\n"
        "Regenerated by `make eval`. Waveforms are synthetic. "
        "Depth-index proxies are not awareness labels. "
        "A VitalDB hold-out is not run.\n\n"
        + (SQ / "results.md").read_text(encoding="utf-8")
        + "\n"
        + (LA / "results.md").read_text(encoding="utf-8")
        + "\n"
        + (PK / "results.md").read_text(encoding="utf-8")
        + "\n"
        + (OP / "results.md").read_text(encoding="utf-8")
    )


def _replace_block(text: str, begin: str, end: str, body: str) -> str:
    start = text.index(begin) + len(begin)
    stop = text.index(end)
    return text[:start] + "\n\n" + body.strip() + "\n\n" + text[stop:]


def patch_readme() -> None:
    path = ROOT / "README.md"
    if not path.exists():
        return
    sq = _read(SQ / "results.json")
    la = _read(LA / "results.json")
    pk = _read(PK / "results.json")
    op = _read(OP / "results.json")
    art = sq["cases"]["artifact"]["per_signal"]["abp"]["usable_fraction"]
    clean = sq["cases"]["clean"]["per_signal"]["abp"]["usable_fraction"]
    body = (
        "| Measurement | Result | Baseline |\n"
        "| --- | --- | --- |\n"
        f"| Clean ABP usable fraction | {clean:.3f} | treat all samples as usable |\n"
        f"| Artifact ABP usable fraction | {art:.3f} | treat flush as hypotension |\n"
        f"| Awareness labels (index) | {la['n_index_awareness']}/{la['n_index']} "
        "| assume labeled |\n"
        f"| Pivot to over-sedation | {la['pivot_to_over_sedation']} | model awareness |\n"
        f"| corr(Ce, depth proxy) | {pk['corr_ce_vs_depth']:.3f} | "
        f"corr(rate, proxy) {pk['corr_rate_vs_depth']:.3f} |\n"
        f"| Over-sedation Ce operating point | "
        f"thr {op['chosen_threshold']:.1f} TPR {op['chosen_tpr']:.3f} | "
        f"FPR {op['chosen_fpr']:.3f} |\n"
    )
    path.write_text(
        _replace_block(
            path.read_text(encoding="utf-8"),
            "<!-- EVAL_TABLE_BEGIN -->",
            "<!-- EVAL_TABLE_END -->",
            body,
        ),
        encoding="utf-8",
    )


def main() -> None:
    memo_path = ROOT / "docs" / "phase-0" / "research-memo.md"
    memo_path.parent.mkdir(parents=True, exist_ok=True)
    memo_path.write_text(render_memo(), encoding="utf-8")
    (ROOT / "docs" / "EVALUATION.md").write_text(render_eval(), encoding="utf-8")
    patch_readme()
    print("wrote memo, EVALUATION.md, README results")


if __name__ == "__main__":
    main()
